# Generated by Django 4.1.4 on 2022-12-27 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='author_id')),
                ('datestart_subscribe', models.DateField(auto_now_add=True, verbose_name='Начало подписки')),
                ('followers', models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='подписчики')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='genre_id')),
                ('title', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='music_id')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('duration', models.TimeField(verbose_name='длительность')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musics.author')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musics.genre')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'ordering': ('-author_id',),
            },
        ),
    ]
