# Generated by Django 4.1.4 on 2023-01-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.author', verbose_name='исполнитель'),
        ),
    ]
