# Generated by Django 4.1.4 on 2023-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='', upload_to='images/', verbose_name='аватарка'),
        ),
    ]
